export const PROJECT_STORIES: Record<string, string> = {
  "ashishkumar4-aqeous":
    "My parents let me use the computer for about an hour a day, so naturally I spent it on game servers. By 11 I was running cPanel and game server setups for some of the bigger Indian hosts, and one of the more popular CS 1.6 (later CS:GO) community servers in India.\n\nAt 15 I wanted to know what actually happens inside a computer, so I started writing my own OS in C and x86 assembly: SMP, multithreading, its own filesystem, ELF loading, a shell and a compositing GUI. Most of it was written on a smartphone over RDP, thanks to that one hour rule. It never got finished (teenage mess and all), but that's still how I learn: I have to build it from scratch before I feel like I get it.",
  "ashishkumar4-flaxdiff":
    "There's a question stuck in my head since I was a kid: can intelligence actually be built? FlaxDiff came out of that. It's a JAX/Flax diffusion library where I implemented 17+ techniques just to understand them, then trained a Stable Diffusion like model from scratch on 128 TPUv4s.",
  "cloudflare-vibesdk":
    "An open source app builder in the spirit of Lovable or Replit, built entirely on Cloudflare and deployable in one click. It's past 5K stars and 1K forks, and a lot of Cloudflare's public AI app building runs on it.",
  flydreamer:
    "Teaching a DreamerV3 style world model agent to fly an FPV drone from vision alone, in simulators I built for it. I fly FPV myself, so this one's personal. Reward shaping is humbling tbh.",
  kinu:
    "My own agent platform, for work that keeps going while I'm away. Every workspace gets a real computer (filesystem, shell, git, Linux containers), and the results and pending decisions wait for me when I'm back. Runs on Cloudflare, or locally with Bun.",
  nimbus:
    "Free POSIX-ish sandboxes on Cloudflare Durable Objects: a WASI runtime, a demand-paged filesystem on SQLite, and Python, Ruby and C running inside, at the edge.",
  dew:
    "What FlaxDiff grew into: one JAX framework for training LLMs, diffusion models and JEPA encoders, from a single GPU to TPU pods.\n\nDiffusion, world models, reinforcement learning: that's the direction I want to keep going in.",
};

const VIT =
  "College is where the tinkering got some structure: Technology Head of the Technology and Gaming Club, flight software for autonomous drones, and a lot of weekends on CTFs.\n\nMy friend Palash and I played as GreyFang, a two person team that hit #7 in India on CTFtime. We came 2nd at the Nullcon Goa hardware CTF in 2020 against university teams of 10+, then went back in 2022 and won it.";
const UMD =
  "In 2024 I left Dyte for a Master's in Applied ML at UMD, mostly for the depth. I worked on Diff2Lip 2, audio-guided lip sync with diffusion, running lots of ablations on the university's SLURM clusters. Meanwhile, Dyte got acquired by Cloudflare.";

export const EXPERIENCE_STORIES: Record<string, string> = {
  vit: VIT,
  "eaf0515c-3715-4c2c-a138-38540c251a0d": VIT,
  hyperverge:
    "My first real job, first as a deep learning intern and then as an ML researcher, on face anti-spoofing: telling a real face from a photo, a screen or a mask. That work helped get the company ISO 30107-3 certified.\n\nMost of my time went into infra though: distributed training and hyperparameter search on TPUs, running thousands of experiments a month. That's where I learned research is mostly an infrastructure problem.",
  dyte:
    "I joined Dyte in 2021 as a founding engineer. Hired for ML, I ended up building Hive, our distributed WebRTC SFU in Go, from scratch: the media backend, protocols, load testing and simulation tooling. It took our stream capacity up about 15x.\n\nI also worked on the AI side of Feta.io (transcription, summaries, RAG). Three years of scaling real-time video taught me more about distributed systems than anything I could have read.",
  umd: UMD,
  "17fc1af8-ce45-40aa-8f95-a1647d2d0931": UMD,
  cloudflare:
    "I joined through an internship in Emerging Technologies & Incubation and went full time after graduating. I created Seal, now Cloudflare OS: workspaces where background agents run in sandboxes, keep their files and open PRs. It went from a solo prototype to its own team and 4.5K+ active users, and it writes about 70% of the PRs in its own repo.\n\nFor its storage I built Mossaic, a versioned, horizontally scalable filesystem, so agents get durable, Drive-like files.",
};

const RETIRED_STORIES = new Set<string>([
  "My parents let me use the computer for about an hour a day, so naturally I spent most of it on game servers. By 11 I was maintaining cPanel and game server setups for some of the bigger Indian game-server hosts, and running one of the more popular Counter-Strike 1.6 (and later CS:GO) community servers in India.\n\nAt 15 I wanted to know what actually happens inside a computer when it runs a program, so I started writing my own OS in C and x86 assembly. Aqeous ended up with SMP multicore support, multithreading, its own filesystem, ELF loading, a shell, a compositing GUI and a small libc. I even ported FASM to it so you could write software for Aqeous on Aqeous. A big chunk of it was written from a smartphone connected to my PC over RDP, because of that one hour rule.\n\nIt never really got finished (teenage mess and all), but that's still how I learn stuff: if something fascinates me, I have to build it from scratch before I feel like I get it.",
  "There's a question that has been stuck in my head since I was a kid: can intelligence actually be built? FlaxDiff came out of that. It's a JAX/Flax diffusion library where I implemented 17+ diffusion techniques, schedulers and samplers, mostly to understand what each one was really doing, and then used it to train a Stable Diffusion like model from scratch on 128 TPUv4s.",
  "I also built VibeSDK, an open source app builder in the spirit of Lovable or Replit, except it's built entirely on Cloudflare's developer platform and you can deploy your own in one click. It has crossed 5K stars and 1K forks on GitHub, and a lot of Cloudflare's public AI app building workflows run on it now.",
  "Lately I've been trying to teach a DreamerV3 style world model agent to fly an FPV drone from vision alone, inside simulation environments I built for it. I build and fly FPV drones myself, so this one is a bit personal. Reward shaping is humbling tbh.",
  "Kinu is my own agent platform, for background work that keeps going while I'm away. Every workspace gets a real computer with a filesystem, shell, git and Linux containers, and when I come back the results and any pending decisions are waiting for me. It runs on Cloudflare Durable Objects, or locally with Bun.",
  "Nimbus gives you free POSIX-ish sandboxes on Cloudflare Durable Objects. There's a WASI runtime, a demand-paged virtual filesystem on top of SQLite, and Python, Ruby and C/Clang compiled to WASM, all running inside the sandbox at the edge.",
  "Dew is what FlaxDiff grew into: one JAX framework for training LLMs, diffusion models and JEPA encoders, from a single GPU up to TPU pods, with FSDP and the usual parallelism tricks.\n\nDiffusion, world models, reinforcement learning: that's the direction I want to keep going in.",
  "College is where the tinkering got some structure. I was the Technology Head of the Technology and Gaming Club, wrote flight software for autonomous drones with a bio-inspired robotics team, and spent a lot of weekends on CTFs.\n\nMy friend Palash and I played as GreyFang, a two person team that got to #7 in India on CTFtime at one point. We came 2nd at the Nullcon Goa hardware CTF in 2020, against university teams of 10+ from IITs, IIITs and Amrita. In 2022 I went back with three friends and we won it.",
  "In 2024 I left Dyte to do a Master's in Applied Machine Learning at UMD, mostly for the ML depth I wanted. I worked on Diff2Lip 2, audio-guided lip sync with diffusion, and ran a lot of ablations on the university's SLURM clusters. While I was there, Dyte got acquired by Cloudflare.",
  "My first real job. I joined HyperVerge in Bengaluru as a deep learning intern in my final year and stayed on as an ML researcher, working on face anti-spoofing: models that can tell a real face from a photo, a screen or a mask. That work helped the company get its ISO 30107-3 certification.\n\nMost of my time went into infra though. I built distributed training and hyperparameter search pipelines on Google TPUs, and once those worked we were running thousands of experiments a month. That's where I figured out research is mostly an infrastructure problem.",
  "I joined Dyte in 2021 as one of its founding engineers. I was hired for ML, but ended up spending most of my time on Hive, a distributed WebRTC SFU we built from scratch in Go. I architected big parts of the media backend, the service protocols and the load testing and simulation tooling, and Hive took our video stream capacity up by about 15x.\n\nI also worked on the AI side of Feta.io (transcription, summaries, RAG) and the eval suites we used to check LLM output. Three years of scaling real-time video taught me more about distributed systems than anything I could have read.",
  "I joined Cloudflare through an internship in Emerging Technologies & Incubation and converted to full time after graduating. There I created Seal, now Cloudflare OS: agentic workspaces where background agents run in sandboxes, keep their files around, talk to you over Google Chat and open PRs. It started as a solo prototype. Today it has its own team, 4.5K+ active users inside Cloudflare, and it writes about 70% of the PRs in its own repo.\n\nFor its storage I built Mossaic, a version-controlled, horizontally scalable filesystem layer, so agents get durable, Drive-like files that survive long runs.",
  "At 15 I wanted to know what actually happens inside a computer when it runs a program, so I started writing my own OS in C and x86 assembly. Aqeous ended up with SMP multicore support, multithreading, its own filesystem, ELF loading, a shell, a compositing GUI and a small libc. I even ported FASM to it so you could write software for Aqeous on Aqeous.\n\nI wrote a big chunk of it from a smartphone connected to my PC over RDP, because the one hour a day rule was still very much a thing. It never really got finished (teenage mess and all), but that's still how I learn stuff: if something fascinates me, I have to build it from scratch before I feel like I get it.",
  "Computer time at home was rationed to an hour a day, which only made me want it more. At 15 I wanted to know what a computer actually does when it runs a program, so I taught myself C and x86 assembly and started writing an operating system, mostly on a smartphone connected to my PC over remote desktop.\n\nIt was never really finished, but it set the way I still learn: if something fascinates me, I have to build it from the ground up before I feel like I understand it.",
  "There is a question that has been stuck in my head since I was a kid: can intelligence actually be built? FlaxDiff was one way of chasing it. I wrote a diffusion library in JAX/Flax, implemented 17+ techniques to understand what each one was really doing, and trained a ~100M-parameter text-to-image model from scratch on 128 TPUv4s.",
  "Alongside Cloudflare OS I created VibeSDK: describe an app in plain language, and it gets generated, deployed and iterated on, entirely on Cloudflare. We open-sourced it, and it has passed 5K stars on GitHub.",
  "Lately I have been teaching a DreamerV3-style world-model agent to fly an FPV drone from vision alone, in simulation environments I built for it. Reward shaping is humbling, tbh.",
  "Kinu is an agent platform that keeps working while you are away. Each workspace gets its own computer, files and memory, in the cloud on Durable Objects or locally, and when you come back its work and pending decisions are waiting for you.",
  "Nimbus gives agents free POSIX-like sandboxes on Durable Objects: a WASI runtime, a virtual file system paged from SQLite, and Python, Ruby and C running inside, at the edge.",
  "FlaxDiff grew up into Dew: one JAX framework for training language models, diffusion models and JEPA encoders, from a single GPU to a TPU pod.\n\nDiffusion, world models, reinforcement learning: that's the direction I want to keep moving in.",
  "College gave the tinkering some structure. For a while the curiosity pointed at breaking things instead of building them: my friend Palash and I started GreyFang, a two-person CTF team that at one point ranked #7 in India. We took second at the Nullcon Goa hardware CTF in 2020 against university teams of ten, then went back in 2022 and won it.\n\nSecurity left me with a habit I still use: assume nothing, verify everything, and read the layer below the one you are debugging.",
  "My first job was at HyperVerge in Bengaluru, as a deep-learning intern in my final year of college and then as an ML researcher. I trained computer-vision models on TPUs to tell a real face from a photo, a screen or a mask, work that supported the company's ISO 30107-3 certification.\n\nThe lesson that stayed was about research itself: progress is mostly an infrastructure problem. Once our pipelines could run 250+ experiments a week, the experiments could finally keep up with our questions.",
  "In 2021 I joined Dyte, a programmable video SDK startup, as one of its founding engineers. I was hired for ML, but soon ended up owning something bigger: designing and building Hive, our distributed WebRTC SFU and media infrastructure, from scratch in Go, and growing its load capacity about fifteenfold.\n\nThree years of scaling real-time video taught me more about production distributed systems than anything I could have read.",
  "In 2024 I went back to school for a Master's in Applied Machine Learning at the University of Maryland, for the depth I wanted. I worked on Diff2Lip 2, audio-guided diffusion lip-sync, running large ablation studies on the university's SLURM clusters. While I was studying, Dyte was acquired by Cloudflare.",
  "I joined Cloudflare through an internship in Emerging Technologies & Incubation and converted to full time after graduating. There I created Seal, now Cloudflare OS: long-running background agents that live in sandboxed workspaces on Durable Objects and do real work, from engineering to operations.\n\nIt grew from a solo prototype into a platform with a dedicated team and thousands of users across the company. Underneath it sits Mossaic, the distributed file system I built for its storage.",
]);

export function isReplaceableStory(story: string | undefined): boolean {
  const text = story?.trim() ?? "";
  return !text || RETIRED_STORIES.has(text);
}
